### ISSUE TITLE
AppMap recording fails with JDK 15,16,17, works with JDK 11

### ISSUE THREAD

**Issue by ptrdvrk** [getappmap/appmap-java#119]
There are errors when recording test cases with newer JDKs, works ok with JDK 11. I've reproduced this issue with multiple Java apps - Spring Petclinic, WebGoat. 

WebGoat Full build log with errors:
[java_webgoat_mapping_errors.log](https://github.com/applandinc/appmap-java/files/7572564/java_webgoat_mapping_errors.log)

**Comment by raduone** [comment]
How is the current status of the project ? AppMap still only works with at most java 11 ?

**Comment by kgilpin** [comment]
Java support remains at version 11, however this is a high priority item so watch this space!
