### ISSUE TITLE
`java.lang.IllegalArgumentException`

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-java#158]
Re-creating [this issue](https://github.com/getappmap/appmap-js/issues/813) in the correct repo.

From this [log](https://portal.azure.com/#view/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-10-23T17%3A13%3A03.934Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-10-23T17%3A13%3A03.934Z%22))%20and%20customDimensions%5B%22appmap.cli.sessionId%22%5D%20contains%20%2282e39d6ecd433c696b846bca10725ea27f4382a29db24c3e4aac7ed00190b846%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%7C%20project-reorder%20%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog):
```
Error: An error occurred while running the command: java -jar $HOME/.m2/repository/com/appland/appmap-agent/1.15.1/appmap-agent-1.15.1.jar -d $HOME/dev/selenium init
The command exited with code 1
> Init AppMap project configuration in directory: $HOME/dev/selenium
> java.lang.IllegalArgumentException
```

**Comment by ahtrotta** [comment]
Re-creating Alan's comment in the [original issue](https://github.com/getappmap/appmap-js/issues/813):

The doc for `subpath` says:
```
Path subpath(int beginIndex,
           int endIndex)
Returns a relative Path that is a subsequence of the name elements of this path.
The beginIndex and endIndex parameters specify the subsequence of name elements. The name that is closest to the root in the directory hierarchy has index 0. The name that is farthest from the root has index count-1. The returned Path object has the name elements that begin at beginIndex and extend to the element at index endIndex-1.

Parameters:
beginIndex - the index of the first element, inclusive
endIndex - the index of the last element, exclusive
Returns:
a new Path object that is a subsequence of the name elements in this Path
Throws:
IllegalArgumentException - if beginIndex is negative, or greater than or equal to the number of elements. If endIndex is less than or equal to beginIndex, or larger than the number of elements.
```

It's not clear from the messages what path is causing the exception. It looks like it might be something under the `selenium` directory. I cloned https://github.com/SeleniumHQ/selenium.git, but the fresh worktree doesn't have `src/main/java` in it, so `appmap-agent-init` doesn't scan anything, and produces `appmap.yml` without problems.

Building selenium is quite complicated, and I couldn't get it to build. It's possible that part of the build will produce a `src/main/java` tree, and scanning that will cause a problem. It's also possible that the user's `selenium` tree contains something other than a clone of this repo.

**Comment by ahtrotta** [comment]
Happened to this user, too: https://applanding.slack.com/archives/C02DU9210Q2/p1666970660971559

**Comment by ahtrotta** [comment]
Happened again [here](https://portal.azure.com/#view/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-12-14T21%3A55%3A15.686Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-12-14T21%3A55%3A15.686Z%22))%20and%20session_Id%20%3D%3D%20%2242835c3dcb94e6ff298361a2c73bc3e12ebca4753dc979781ceaa695d98cb40e%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%2Cexception%3DcustomDimensions%5B%22appmap.debug.exception%22%5D%7C%20project-reorder%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog%2Cexception)

**Comment by apotterri** [comment]
It looks like this happens when there's a class in the unnamed package. For example, if a project contains `src/main/java/Foo.java`, you'll see this exception.

Seems like we should just ignore this case and continue scanning.
