### ISSUE TITLE
Crash trying to get the URL for an http_client_request

### ISSUE THREAD

**Issue by apotterri** [getappmap/appmap-java#177]
Details starting [here](https://github.com/getappmap/appmap-java/issues/175#issuecomment-1527538362).

Looks like implementing the other overloads for the `execute` should resolve this.

**Comment by apotterri** [comment]
@tokazio I should have a fix for this later today or tomorrow, though I'm not sure whether it's complete enough.

Would you be willing to try it out and see whether it works for you?

Thanks!

**Comment by tokazio** [comment]
Yes i Can try tomorrow, how Can i try ?

**Comment by apotterri** [comment]
I'll attach a jar here as soon as I can.

**Comment by tokazio** [comment]
Ok nice, thanks

**Comment by apotterri** [comment]
Ok, here's a new version of the agent:
[appmap-1.17.2-SNAPSHOT.jar.zip](https://github.com/getappmap/appmap-java/files/11384562/appmap-1.17.2-SNAPSHOT.jar.zip)

I believe it should resolve the crash you found. It's possible, however, that it won't completely capture responses from an external service. Can you give it a try, and see how it works for you?

**Comment by apotterri** [comment]
Ok, thanks, seems like we're making progress!

As far as getting better AppMaps, can you share the `appmap.yml` from your project, please? 

And, as far as that ClassNotFoundException, can you provide the complete commandline that's getting used to start the service? fastjson should be getting embedded in the `appmap` jar file, and the dependency on it shouldn't be leaking out....

**Comment by tokazio** [comment]
```
name: xxx-service
packages:
  - path: io.group
```
Something like this (at the build.gradle level)

I'm in a multi module gradle project

**Comment by tokazio** [comment]
my VM options
```
-javaagent:/Users/bidule/appmap-agent-1.17.2.jar
-Dappmap.record.privat=true
-Dappmap.recording.auto=true
-Dappmap.output.directory=/Users/romain/appmap-record
```

**Comment by apotterri** [comment]
So, your application classes are in the package `io.group`, correct?

For the command line, what's the classpath getting set to? Does it include `appmap-agent-1.17.2.jar`. If so, does the error still happen if you remove it? (It shouldn't be necessary for it to be on the classpath.)

**Comment by tokazio** [comment]
removing `implementation 'com.alibaba:fastjson:2.0.28'` 
i've got the error but it seems to not prevent the recording, that's ok

yes they're in some sub packages from `io.group` like `io.group.service.xxx`

i see the agent and config in the launching command line of intellij, i see a second `-javaagent` with the ij one
appmap-agent-1.17.2.jar only as a `-javaagent`, not in `-classpath`

oO i've got the whole data in my last try... lol i don't know what i've changed... 

nice ^^

**Comment by apotterri** [comment]
Oh, hey, FWIW, I noticed a typo here, too: `-Dappmap.record.privat=true` should be `-Dappmap.record.private=true`.

**Comment by tokazio** [comment]
Yes, i've corrected that. 

I've got some appmap for my services!

I've drag and drop some in intellij but after 3 or 4 it has stop working and showing me the json insteadof the diagram.

I've restarted intellij but nothing works.

I haven't found another way to open the files.

**Comment by apotterri** [comment]
Excellent, thanks very for trying out the fix. I'll get it released as soon as possible.

@ghamelin Seems like there's an IntelliJ issue here, too. Can you weigh in, please?

**Comment by ghamelin** [comment]
I will dig into it and see what I can find I haven't encountered this issue but I'd be happy to look into it.

**Comment by brikelly** [comment]
@tokazio one thing you could try (temporarily) is to try to open those maps in VS Code (after installing the AppMap extension there too).

**Comment by tokazio** [comment]
Yes, i'll tryit soon.
Maybe i Can grab a log Somewhere for this opening issue ?

**Comment by ghamelin** [comment]
I experienced a similar issue I have submitted a ticket for getting it fixed.

**Comment by apotterri** [comment]
Issue for drag-and-drop in IntelliJ extension is here: https://github.com/getappmap/appmap-intellij-plugin/issues/259 .
