### ISSUE TITLE
URL domain in generated appmap.yml comment needs to be appmap.io

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-java#216]
https://github.com/getappmap/appmap-java/blob/c89265369ecdc8016645bb59d4fcba6f6f99bafd/agent/src/main/java/com/appland/appmap/config/AppMapConfig.java#L189C87-L189C87

The link still works, but we should change it.

**Comment by Sweetdevil144** [comment]
Hello @brikelly. I would like to work on this issue!!

**Comment by Sweetdevil144** [comment]
Is this issue open?

**Comment by brikelly** [comment]
Hi @Sweetdevil144 , sure, as an open source company we are happy to accept PRs

**Comment by Sweetdevil144** [comment]
The issue is fixed. Following changes were made :

```java
pw.println("# https://appland.com/docs/reference/appmap-java.html#configuration");
```
was converted to
```java
pw.println("# https://appmap.io/docs/reference/appmap-java.html#configuration");
```
