### ISSUE TITLE
Request recordings should not occur for media assets downloads

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-java#231]
Currently, Java request recordings show up or all kinds of CSS, image, and HTML `GET` requests. These are noisy and should be disabled.

**Comment by kgilpin** [comment]
This is disabled in the client tooling, we don't normally make it the
agent's job to figure this out.

**Comment by kgilpin** [comment]
This is configured in the client tooling, e.g. the diagrams and scanner, we don't require the Agent to make this distinction.

**Comment by brikelly** [comment]
It's not the `Hide media requests` control I'm referring to, though - it's the fact that lots of per-request maps for media requests get created and then show up in our AppMap list in the UI, and create more work for the indexer and scanner to deal with.

For example:
<img width="246" alt="Screenshot 2023-10-13 at 6 58 11 PM" src="https://github.com/getappmap/appmap-java/assets/573108/43411018-5512-41b6-a0cd-80f5fefea8fd">

All that said, I just updated the Java agent that IntelliJ was using and it looks a whole lot better. The only asset-like request was the one for `vets.html` in the graphic above, and that map shows a call to the DB to retrieve some of the content, so it's a legit map to record. @apotterri did you happen to fix this issue recently?

**Comment by brikelly** [comment]
Here's how things look like in Python / Flask:

![Image](https://github.com/getappmap/appmap-java/assets/573108/fc4e6e49-72eb-40fb-a7b6-451576585982)

So I think I just mis-remembered which language this issue was present in. I'll file this as a Python issue and close this one.

**Comment by apotterri** [comment]
Actually, it *was* broken for Java as well. I fixed it for Spring apps in v1.20.1. It's still broken for other frameworks, though. Dunno whether you want to reopen it based on that?

**Comment by kgilpin** [comment]
Ok. We could also fix this in the code editor. For example browser debugger tools will have an option to hide media requests. Getting this right in all the agents and frameworks is going to be hard.
